const axios = require('axios');
const cheerio = require('cheerio');
const { sanitizeRecipe } = require('../videoToRecipeService');

async function extractRecipeSimple(url) {
  try {
    console.log(`🌐 Fetching: ${url}`);
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);

    // Remove noise
    $('script, style, nav, header, footer, aside, .ad, .comment, .sidebar').remove();

    // Extract structured parts
    const title = extractTitle($);
    const description = extractDescription($);
    const ingredients = extractIngredientsStructured($);
    const steps = extractStepsStructured($);
    const metadata = extractMetadata($);

    // Build a clean text representation for the LLM
    let cleanText = '';
    if (title) cleanText += `Title: ${title}\n\n`;
    if (description) cleanText += `Description: ${description}\n\n`;
    if (ingredients.length) {
      cleanText += 'INGREDIENTS:\n' + ingredients.join('\n') + '\n\n';
    }
    if (steps.length) {
      cleanText += 'INSTRUCTIONS:\n' + steps.join('\n') + '\n\n';
    }
    if (metadata.prep) cleanText += `Prep time: ${metadata.prep}\n`;
    if (metadata.cook) cleanText += `Cook time: ${metadata.cook}\n`;
    if (metadata.servings) cleanText += `Servings: ${metadata.servings}\n`;

    // If we got nothing, fall back to whole body text
    if (!cleanText) {
      console.log('⚠️ No structured content found, using full body text');
      cleanText = $('body').text().replace(/\s+/g, ' ').trim();
    }

    // Truncate if too long
    const maxLength = 8000;
    const textForLLM = cleanText.length > maxLength ? cleanText.slice(0, maxLength) + '…' : cleanText;
    console.log(`📄 Extracted text length: ${textForLLM.length} chars`);
    console.log('📄 Sample:', textForLLM.substring(0, 500));

    // Send to LLM with a focused prompt
    const recipe = await generateRecipeFromWebsiteText(textForLLM, url);

    console.log('✅ Recipe generated by LLM');
    return recipe;
  } catch (error) {
    console.error('❌ Simple extraction failed:', error);
    throw error;
  }
}

// ---------- Structured extraction helpers (same as before) ----------
function extractTitle($) {
  const selectors = [
    'meta[property="og:title"]',
    'meta[name="twitter:title"]',
    'h1',
    '.recipe-title',
    '#recipe-title'
  ];
  for (const sel of selectors) {
    if (sel.startsWith('meta')) {
      const content = $(sel).attr('content');
      if (content) return content.trim();
    } else {
      const text = $(sel).first().text().trim();
      if (text) return text;
    }
  }
  return null;
}

function extractDescription($) {
  const selectors = [
    'meta[name="description"]',
    'meta[property="og:description"]',
    '.recipe-description',
    '#recipe-description',
    '.description'
  ];
  for (const sel of selectors) {
    if (sel.startsWith('meta')) {
      const content = $(sel).attr('content');
      if (content) return content.trim();
    } else {
      const text = $(sel).first().text().trim();
      if (text && text.length > 20) return text;
    }
  }
  return null;
}

function extractIngredientsStructured($) {
  const ingredients = [];
  const containerSelectors = [
    '.ingredients',
    '#ingredients',
    '.recipe-ingredients',
    '.ingredients-list',
    '[itemprop="recipeIngredient"]',
    '.ingredients-group'
  ];

  let $container = null;
  for (const sel of containerSelectors) {
    $container = $(sel).first();
    if ($container.length) break;
  }

  if ($container && $container.length) {
    $container.find('li').each((i, el) => {
      const text = $(el).text().trim();
      if (text && text.length > 3) ingredients.push(text);
    });
  } else {
    $('ul, ol').each((i, ul) => {
      const text = $(ul).text();
      if (text.match(/\d+\s*(g|ml|cup|tbsp|tsp|oz|lb)/i)) {
        $(ul).find('li').each((j, li) => {
          const line = $(li).text().trim();
          if (line) ingredients.push(line);
        });
        return false;
      }
    });
  }
  return [...new Set(ingredients)];
}

function extractStepsStructured($) {
  const steps = [];
  const containerSelectors = [
    '.instructions',
    '#instructions',
    '.recipe-instructions',
    '.steps',
    '.directions',
    '[itemprop="recipeInstructions"]',
    '.recipe-directions'
  ];

  let $container = null;
  for (const sel of containerSelectors) {
    $container = $(sel).first();
    if ($container.length) break;
  }

  if ($container && $container.length) {
    $container.find('li, p').each((i, el) => {
      const text = $(el).text().trim();
      if (text && text.length > 10) steps.push(text);
    });
  } else {
    $('ol').each((i, ol) => {
      $(ol).find('li').each((j, li) => {
        const text = $(li).text().trim();
        if (text) steps.push(text);
      });
    });
  }
  return steps;
}

function extractMetadata($) {
  const meta = { prep: null, cook: null, servings: null };
  const bodyText = $('body').text();
  
  const servingsMatch = bodyText.match(/(?:serves|servings?|yield|portions?)\s*:?\s*(\d+)/i);
  if (servingsMatch) meta.servings = servingsMatch[1];

  const prepMatch = bodyText.match(/(?:prep(?:aration)?\s*time\s*:?\s*)(\d+)\s*(?:min|minutes?|hour|h)/i);
  if (prepMatch) meta.prep = prepMatch[1] + ' min';

  const cookMatch = bodyText.match(/(?:cook\s*time\s*:?\s*)(\d+)\s*(?:min|minutes?|hour|h)/i);
  if (cookMatch) meta.cook = cookMatch[1] + ' min';

  return meta;
}

// ---------- LLM call with improved prompt ----------
async function generateRecipeFromWebsiteText(pageText, sourceUrl) {
  if (!process.env.GROQ_API_KEY) {
    throw new Error("GROQ_API_KEY not set in environment");
  }

  const systemPrompt = `You are an expert recipe parser. Extract the recipe from the provided text, which comes from a recipe webpage. Follow these rules exactly:

1. **Title** – Use the recipe title (often at the top). If multiple titles, choose the most specific one.

2. **Description** – A short summary (max 1000 chars). If not present, you may leave empty.

3.0  **UNIT CONSTRAINT - USE METRIC SYSTEM BY DEFAULT:**
   Use ONLY: g, kg, ml, l, tsp, tbsp, pc (pieces), pinch, dash
   - Separate quantity from unit: 
     * quantity: "1", "1/2", "2-3", or number
     * unit: "kg", "g", "ml", "tbsp", "tsp", "pc", "pinch", etc.
    - If both imperial and metric are present, use the metric version only (e.g., "1 ½ cups (300 g) sugar" → quantity: "300", unit: "g").
    - If there is only mention of the imperial units then just do the recipe in imperial units.

3. **Ingredients** – List all ingredients, grouped into sections exactly as they appear in the text. Look for section headings. Assign each ingredient to the most recent heading. If no heading, use "Main".
   - For each ingredient line, extract:
     - "name": the ingredient name (cleaned, e.g., "dark chocolate couverture").
     - "quantity": the amount as a decimal (e.g., "3", "0.5", "500"). If a range is given (e.g., "4-5 cups"), use the first number.
     - "unit": the unit of measurement. Use metric (g, kg, ml, l, tsp, tbsp, pc, pinch, dash) if available. If the line contains both imperial and metric (e.g., "1 ½ cups (300 g) sugar"), **use the metric version only** (quantity and unit in g, ml, etc.). If no unit is given (e.g., "3 eggs"), default to "pc".
   - **Do not create duplicate ingredients** from a single line – combine the information into one object.
   - Group ingredients by component, that will have the same name as the steps (for example, "Prepare", "Assemble", "Cook", "Finish", "Garnish")
  - Always put the main ingredient first in the ingredient name (e.g., olive oil should be oil olive, white wignegar should be vinegar white wine, etc.)


4. **Steps** 
    - Write clear, numbered, chronological cooking steps
    - Group steps into logical sections (for example, "Prepare", "Assemble", "Cook", "Finish", "Garnish")
    - Each section should have a descriptive title
    - Each step within a section should be 2-3 sentences with actionable details.
    – List the cooking instructions in order, grouped into sections if headings exist. 
    - Each step should be a clear sentence. 
    - Include any timing mentioned (e.g., "bake for 30 minutes" → duration_minutes: 30). If a range (e.g., "45-50 minutes"), use the first number.

5. **Metadata** – Extract the following if present:
   - Servings (portions): look for "Yield:", "Servings:", "Serves:".
   - Prep time, cook time, total time: look for "Prep Time:", "Cook Time:", "Total Time:". Use minutes (integer). If a range, take the first number.
   - **You MUST include these fields in the output JSON, even if they are null.** Do not omit them.
   - Difficulty: look for words like "easy", "medium", "hard". Map to "Easy", "Medium", "Hard".
   - Course type: e.g., "Dessert", "Main Course", "Appetizer". Often found in categories.
   - Meal type: e.g., "Breakfast", "Lunch", "Dinner", "Snack".
   - Cuisine type: e.g., "Italian", "French". If unclear, use "Homemade".

6. **Output JSON** – Must match the exact structure below. Do not include any other text.

{
  "title": "Recipe Name",
  "description": "Brief description",
  "portions": 4,
  "prep_time": 20,
  "cook_time": 35,
  "total_time": 55,
  "difficulty": "Medium",
  "course_type": "Dessert",
  "meal_type": "Dinner",
  "cuisine_type": "Italian",
  "ingredients": [
    {
      "name": "flour",
      "quantity": "2.5",
      "unit": "cup",
      "section": "Cake Batter"
    }
  ],
  "steps": [
    {
      "section": "Prepare",
      "step_number": 1,
      "instruction": "Preheat oven to 180°C...",
      "duration_minutes": 10,
      "sub_steps": ["Use parchment paper", "Grease the pan"]
    }
  ]
}

// In generateRecipeFromWebsiteText, add to systemPrompt:
// "Look for section headings in ALL CAPS (e.g., GANACHE, CHOCOLATE CAKE, CRUNCH) 
//  and group subsequent ingredients under that section until the next heading."

  7. **VERY IMPORTANT CRITICAL NOTES:**
    - Always use CELSIUS for temperatures with Fahrenheit in parentheses (if mentionned)
    - Use in priority the metric units system for all ingredient quantities (g, kg, ml, l) pieces (pc), unless the original recipe only uses imperial units, in which case you can retain those units.
    - Never use Fractions in quantities !! (like 1/2 or 3/4) always use decimals (0.5, 0.75) for clarity and consistency
    - Steps must be logical, chronological, and detailed
    - Include warnings, tips, and techniques
    - Each section should have 1-7 steps with clear progression
    - Duration should be in minutes (or null if unknown) but it must alway be realistic, and complete minutes (not around 2min).
    - sub_steps should be an array of brief bullet points with extra tips
    - Do NOT include any text outside the JSON object
`;

  const userMessage = `Extract the recipe from this webpage text (source: ${sourceUrl}):\n\n${pageText}`;

  try {
    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userMessage }
        ],
        temperature: 0.1,
        max_tokens: 4000,
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${process.env.GROQ_API_KEY}`,
          'Content-Type': 'application/json'
        },
        timeout: 30000
      }
    );

    if (!response.data.choices?.[0]?.message?.content) {
      throw new Error('Invalid response from Groq API');
    }

    const content = response.data.choices[0].message.content;
    let recipeData;
    try {
      recipeData = JSON.parse(content);
    } catch (parseErr) {
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        recipeData = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('Failed to parse JSON from LLM response');
      }
    }

    return sanitizeRecipe(recipeData);
  } catch (error) {
    console.error('❌ LLM call failed:', error.message);
    throw error;
  }
}

async function fetchHtml(url) {
  const response = await axios.get(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.5',
      'Accept-Encoding': 'gzip, deflate, br',
      'DNT': '1',
      'Connection': 'keep-alive',
      'Upgrade-Insecure-Requests': '1',
      'Sec-Fetch-Dest': 'document',
      'Sec-Fetch-Mode': 'navigate',
      'Sec-Fetch-Site': 'none',
      'Cache-Control': 'max-age=0',
    },
    timeout: 15000, // increased timeout
    maxRedirects: 5,
    validateStatus: status => status < 400, // allow only 2xx and 3xx
  });
  return response.data;
}

module.exports = { extractRecipeSimple, generateRecipeFromWebsiteText };